services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    command: sh -c "npx prisma migrate deploy && node dist/src/main.js"
    volumes:
      - ./backend/.env:/app/.env